### ISSUE TITLE
don't submit a gif

### ISSUE THREAD

**Issue by ungoldman** [ngoldman/coolgifs.neocities.org#1]
# No longer accepting submissions!<br> This site is retired! Good night 🌙 

---

# ~Hello there!~

Are you perhaps interested in **submitting a gif** for display on **"THE COOL GIFS SITE™"**?

If so, **you** have come to **the ~right~ wrong place**!
## how to submit
- You **can't** drag and drop a gif directly into the comment box below!
- ~You can also just share a link to a gif but that's more work for me!~
## acceptance criteria
- ~**file size**: 1MB maximum~
- ~**background**: transparent~
- ~**dimensions**: 200px by 200px maximum (exceptions made for coolness)~
- must be **cool** 😎 

~Gifs larger than 200x200 are always sized down using _CSS3_ so please keep that in mind!~
## ~please stay cool my friends~

![](http://bestanimations.com/Text/Cool/cool-64.gif)

**Comment by mbcharbonneau** [comment]
![4lt7jmr](https://cloud.githubusercontent.com/assets/4793/18369228/601b057a-75d9-11e6-92e1-944c09f42c07.gif)

**Comment by ungoldman** [comment]
Thank you @mbcharbonneau that is indeed a cool gif, but sadly it does not have a transparent background so it does not fit in within the confines of the carefully crafted aesthetic guidelines of THE COOL GIFS SITE™.

However while you are here I would like your opinion on how to mature an equally lucrative internet property: http://meowl.party. To date I only have 16 meowls (see [here](https://github.com/ungoldman/meowl.party/tree/gh-pages/meowls)), all of which I received from you with great gratitude. I have suggested to @nikolaswise that it may be wise to begin producing original works for that property. Your thoughts and contributions are welcome.

**Comment by mbcharbonneau** [comment]
oh dang I didn't read all the rules 😳

**Comment by joppiesaus** [comment]
I don't know if this infamous bone head has enough quality for **THE COOLEST GIF SITE™**, you'll have to carefully decide. It also might spook humans visiting **THE COOLEST GIF SITE™**. Thank you.
![skull](https://cloud.githubusercontent.com/assets/5196627/18616500/2d411fea-7dbd-11e6-9dc9-b423c9da42a2.gif)

**Comment by ungoldman** [comment]
Thank you for your spooky submission, @joppiesaus!

Your gif has been added to **"THE COOL GIFS SITE™"**.

![screen shot 2016-09-18 at 10 54 40 am](https://cloud.githubusercontent.com/assets/427322/18617852/e6a566b4-7d8e-11e6-94e9-b90fac5fc522.png)

So spooky!

**Comment by MixelDood256** [comment]
![dat_circle](https://cloud.githubusercontent.com/assets/26421788/23927801/1ccfa282-0970-11e7-9526-004d225b2df1.gif)

**Comment by ungoldman** [comment]
Hi @MixelDood256! Thank you for your thoughtful submission. However I am sad to say that I am unable to accept it, as it does not have a transparent background and therefore doesn't quite work with the look of the site. See the screenshot below illustrating the problem:

![screen shot 2017-03-14 at 5 38 59 pm](https://cloud.githubusercontent.com/assets/427322/23928497/4d04c7ea-08dd-11e7-8895-c8ba4acbdde0.png)

I hope to see another submission from you in the future! I am sure you can find one that meets the guidelines mentioned at the top of this thread. 😁

**Comment by TheMidnightSnack** [comment]
![welcome1](https://user-images.githubusercontent.com/40611738/51800146-1037e400-21e0-11e9-9286-fc1b5503b101.gif)

**Comment by rangeTonic** [comment]
<details>
<summary>Eighteen hand-picked gifs from some pirate shareware CD.</summary>
<ol>
<li><img src="https://user-images.githubusercontent.com/10710554/59765776-d9a65700-92af-11e9-83b4-d3e3cae26fb2.gif"></li>
<li><img src="https://user-images.githubusercontent.com/10710554/59765903-2427d380-92b0-11e9-9693-39d83fbc028a.gif"></li>
<li><img src="https://user-images.githubusercontent.com/10710554/59765922-2e49d200-92b0-11e9-968a-a4891f7859be.gif"></li>
<li><img src="https://user-images.githubusercontent.com/10710554/59765930-3275ef80-92b0-11e9-88a7-9dfb67117ea4.gif"></li>
<li><img src="https://user-images.githubusercontent.com/10710554/59765940-36097680-92b0-11e9-887d-d49a055160c0.gif"></li>
<li><img src="https://user-images.githubusercontent.com/10710554/59765946-386bd080-92b0-11e9-8155-9facdaf4cdaa.gif"></li>
<li><img src="https://user-images.githubusercontent.com/10710554/59765953-3ace2a80-92b0-11e9-83c5-aa42ee3ed957.gif"></li>
<li><img src="https://user-images.githubusercontent.com/10710554/59765957-3c97ee00-92b0-11e9-9dc9-794786225a59.gif"></li>
<li><img src="https://user-images.githubusercontent.com/10710554/59765960-3e61b180-92b0-11e9-9588-0509f0e51b67.gif"></li>
<li><img src="https://user-images.githubusercontent.com/10710554/59765965-40c40b80-92b0-11e9-902d-57137998512d.gif"></li>
<li><img src="https://user-images.githubusercontent.com/10710554/59765973-428dcf00-92b0-11e9-966e-43abfd30acf2.gif"></li>
<li><img src="https://user-images.githubusercontent.com/10710554/59765974-44579280-92b0-11e9-8e53-2ddac2bd97bb.gif"></li>
<li><img src="https://user-images.githubusercontent.com/10710554/59765996-50435480-92b0-11e9-9161-fc2cceacbc46.gif"></li>
<li><img src="https://user-images.githubusercontent.com/10710554/59765977-46215600-92b0-11e9-86a2-bd9a43656e14.gif"></li>
<li><img src="https://user-images.githubusercontent.com/10710554/59765983-49b4dd00-92b0-11e9-9803-9b17eb375b8c.gif"></li>
<li><img src="https://user-images.githubusercontent.com/10710554/59765985-4b7ea080-92b0-11e9-853e-156c7b043293.gif"></li>
<li><img src="https://user-images.githubusercontent.com/10710554/59765989-4d486400-92b0-11e9-9884-faa66c90b8a7.gif"></li>
<li><img src="https://user-images.githubusercontent.com/10710554/59765992-4e799100-92b0-11e9-966b-01dc5d8c60ce.gif"></li>
</ol>
</details>

**Comment by ungoldman** [comment]
@retardTonic thank you! 18 is a duplicate of 10, but this is a good collection.

@TheMidnightSnack I have not included your gif because... it is not cool! thank you and keep searching.

**Comment by TheMidnightSnack** [comment]
Okay, I see where I went wrong. I have a few more:
![Seite0_IMG_OBJ10](https://user-images.githubusercontent.com/40611738/60027308-15e00b80-9652-11e9-9ca0-946e2e62cc14.gif)
![chickenwithsunglasses](https://user-images.githubusercontent.com/40611738/60027319-1a0c2900-9652-11e9-8bae-6eb7da1b9f45.gif)
![macaroni_ani1](https://user-images.githubusercontent.com/40611738/60027325-1d9fb000-9652-11e9-87e3-504ebae75079.gif)
![crab](https://user-images.githubusercontent.com/40611738/60027312-18dafc00-9652-11e9-926d-869ba2d26539.gif)

**Comment by ungoldman** [comment]
That crab... is extremely cool! Thank you for your contribution @TheMidnightSnack.

**Comment by ungoldman** [comment]
@TheMidnightSnack & @retardTonic:

Your excellent contributions have been added along with a few choice finds,
for a grand a total of **33 NEW GIFS**.

All are now "_online_" at https://coolgifs.neocities.org.

This update also includes a few extra features:

- 🔉 20 (HIDDEN) SOUNDS
- 💬 SPEECH SYNTHESIS
- 🌞 INTRODUCING "LightMode™"

**Comment by atmjam** [comment]
![big12](https://user-images.githubusercontent.com/52430679/60471252-e755c800-9c31-11e9-8239-e46a84a5ecb9.gif)
is this gif cool enough for the party

**Comment by ungoldman** [comment]
I tried adding your gif @atmjam but... there seems to be an error. Please try again! Thank you 🙏 
![error](https://user-images.githubusercontent.com/427322/60485409-beddc600-9c51-11e9-88e2-f94b7bdb1f4c.gif)

**Comment by atmjam** [comment]
https://medulla.neocities.org/decorations/big12.gif
hopefully this upload should work better

**Comment by Orbzilla** [comment]
![alien_dancing](https://user-images.githubusercontent.com/52539671/60673849-c2866e00-9e46-11e9-9f40-dece9e71cce9.gif)

**Comment by Orbzilla** [comment]
![dancing baby](https://user-images.githubusercontent.com/52539671/60673891-d9c55b80-9e46-11e9-9d56-9053931b10d8.gif)

**Comment by DvToons** [comment]
![sonic](https://user-images.githubusercontent.com/54008958/62840842-3b5ebe00-bc6e-11e9-9720-70fcc35098b6.gif)

**Comment by izzint** [comment]
heres my gif size it down plz 
![source](https://user-images.githubusercontent.com/44090193/63212087-93ae1980-c0cd-11e9-87ca-3fadbcff41ee.gif)

**Comment by m0zaix** [comment]
![Bear](https://user-images.githubusercontent.com/55955480/65835713-cf055000-e2e9-11e9-885c-683585ee9f37.gif)

**Comment by liztere** [comment]
![animated-scales-image-0008](https://user-images.githubusercontent.com/13914299/69910013-534f7e80-13d2-11ea-9f5b-308004457414.gif)


![bbcam](https://user-images.githubusercontent.com/13914299/69910016-59ddf600-13d2-11ea-9ac2-bb813b3b34ba.gif)


![Fire-breathing-dragon-head-animation](https://user-images.githubusercontent.com/13914299/69910019-619d9a80-13d2-11ea-9ba3-7a686019b57d.gif)


![ShyUnsightlyCorydorascatfish-small](https://user-images.githubusercontent.com/13914299/69910022-6d895c80-13d2-11ea-99fe-83ff66a58b9a.gif)


![ymbabykick](https://user-images.githubusercontent.com/13914299/69910023-71b57a00-13d2-11ea-9147-e91676fe4b95.gif)

![w36W5ps](https://user-images.githubusercontent.com/13914299/69910041-9e699180-13d2-11ea-8dfe-578db98143c3.gif)



have so much more but i'll drop these for now

**Comment by DetectiveLavender** [comment]
![ranma](https://user-images.githubusercontent.com/42054989/71317487-a8613c00-2436-11ea-8f2b-05556929720a.gif)

**Comment by R3Ked** [comment]
(this one wasn't transparent)

**Comment by R3Ked** [comment]
I have a cool gif.
![rainbowspinningstar](https://user-images.githubusercontent.com/20342336/80733211-41c5ec00-8ac2-11ea-956f-2068f7046776.gif)

**Comment by R3Ked** [comment]
It looks like you like spinning gifs, so I got you a spinning Pikachu
![pikaspin](https://user-images.githubusercontent.com/20342336/81362164-0cf2ff80-9095-11ea-853c-565a084aa9d8.gif)

**Comment by R3Ked** [comment]
are you still checking on this

**Comment by ungoldman** [comment]
nope

**Comment by ungoldman** [comment]
You've all done some great work here but I'm a tired old man. I encourage you to follow @siky112's example and open a PR to add it yourself if you feel deeply about it.

Thanks all!
